version: '2'
services:
    countbuddyv3-app:
        image: countbuddyv3
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://countbuddyv3-mysql:3306/countbuddyv3?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    countbuddyv3-mysql:
        extends:
            file: mysql.yml
            service: countbuddyv3-mysql
